- company: JP Morgan & Chase
  source_type: api
  handler: jpmorgan
  last_saved: '2026-02-05'
  max_saved_jobs: 10
- company: Zeta
  source_type: api
  handler: zeta
  last_saved: '2026-02-04'
  max_saved_jobs: 10
- company: Amazon
  source_type: api
  handler: amazon
  last_saved: '2026-02-04'
  max_saved_jobs: 10
- company: Microsoft
  source_type: api
  handler: microsoft
  last_saved: '2026-02-05'
  max_saved_jobs: 10
