- company: JP Morgan & Chase
  source_type: api
  handler: jpmorgan
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Zeta
  source_type: api
  handler: zeta
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Amazon
  source_type: api
  handler: amazon
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Microsoft
  source_type: api
  handler: microsoft
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Media.net
  source_type: html
  handler: mediadotnet
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Goldman Sachs
  source_type: api
  handler: goldman_sachs
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Arcesium
  source_type: api
  handler: arcesium
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: DE Shaw
  source_type: html
  handler: de_shaw_india
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Atlassian
  source_type: html
  handler: atlassian
  last_saved: '2026-02-11'
  max_saved_jobs: 999
- company: Intuit
  source_type: html
  handler: intuit
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Infosys
  source_type: api
  handler: infosys
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: Cisco
  source_type: api
  handler: cisco
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: EY
  source_type: html
  handler: ey
  last_saved: '2026-02-14'
  max_saved_jobs: 999
- company: KPMG
  source_type: api
  handler: kpmg
  last_saved: '2026-02-14'
  max_saved_jobs: 333
